/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Factories {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  location: string | null;
  metadata: Generated<Json>;
  name: string;
  organization_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Gateways {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  factory_id: string;
  firmware_version: string | null;
  gateway_id: string;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  metadata: Generated<Json>;
  model: string | null;
  name: string;
  password_encrypted: string;
  updated_at: Generated<Timestamp>;
  url: string;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface DB {
  factories: Factories;
  gateways: Gateways;
  organizations: Organizations;
  pgmigrations: Pgmigrations;
}
